# Apenas use "docker compose up" na linha de comando e pronto! servidor rodando em http://localhost:8080.
# Todas vez que for fazer um push apague os arquvos da pasta "bd" no diretorio: app/Database/bd.

services:
  front-end:
    image: node:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    entrypoint: ["npm", "start"]

  back-end:
    image: php:8.1-fpm-alpine
    ports:
      - "443:443"
    volumes:
      - .:/var/www/html
    entrypoint: ["php", "-S", "0.0.0.0:8080"] # iniciando o servidor em 0.0.0.0:8080 para que possa ser acessado fora do container

  data-base:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: pi_db
      MYSQL_USER: pi
      MYSQL_PASSWORD: pi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./app/Database/bd:/var/lib/mysql # Persistência de dados do banco de dados.
      - ./app/Database/sql:/docker-entrypoint-initdb.d # Script para criar tabelas.
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "9090:9090"
    environment:
      - PMA_ARBITRARY=1
